### ISSUE TITLE
Group Call?

### ISSUE THREAD

**Issue by brianerdelyi** [CryptoConsortium/CCSS#2]
Is there any interest in having a group call on Skype or Google Hangouts?

I'd like to briefly get to know those involved in helping to create this standard and discuss some initial ideas.  I'm in Atlantic Time Zone but would be happy to coordinate something that fits everyone.

If I get emails addresses to brian.erdelyi@gmail.com I'd be happy to coordinate and organize the call using www.doodle.com.

**Comment by Abstrct** [comment]
Hi Brian, 

We have setup a slack site where we are trying to focus most of the discussion. This way there is a log of all chat that can be made publicly available. I have gone ahead and sent out an invite to your email so if you see that, please accept!

I think Skype and google hangout discussions will be much easier to arrange in that setting. 

Thanks again for your support, 
Josh
