### ISSUE TITLE
Certification Processing; no contact info for support

### ISSUE THREAD

**Issue by blakemiles** [CryptoConsortium/CCSS#24]
_Note: This may not be the right place for it, but couldn't find a support contact__

As above, I recently passed the CBP exam and it says certification processing. Just curious as to the timeline for that to complete.

Also, please put in a contact form :) would help others! Thanks!

**Comment by mperklin** [comment]
This repository is for issues with the CCSS, not with the CBP.

C4 accepts support requests via their website at https://cryptoconsortium.org and lists contact details directly on their homepage.
