### ISSUE TITLE
Certification Verification Bug

### ISSUE THREAD

**Issue by Enegnei** [CryptoConsortium/CCSS#46]
I discovered a problem with the certification verification / lookup option on the C4 website.

1. Navigate down the homepage of [C4](https://cryptoconsortium.org), click on "[Verify a Certification](https://cryptoconsortium.org/lookup/)"
2. On the Lookup page, enter a certification ID. For example, mine is: 5ae571. It is the ID for my Certified Bitcoin Professional (CBP) certificate.
3. In the drop-down menu, select 'Crypto Currency Security Standard Auditor (CCSSA).'
4. Click 'Verify.'
5. Name, certification and expiration dates appear, as well as the message "Professional Found." This is incorrect, as that ID only applies to the CBP certification.

![C4WebsiteBug](https://user-images.githubusercontent.com/15363282/64831489-32973a00-d5d6-11e9-8737-bf42df1cbcb5.png)

I assume the lookup is only checking whether the ID matches one in the C4 certification database, but it is ignoring what was selected in the drop-down menu. While there is probably / hopefully a low chance of this actually happening, someone could deceive a potential employer, client, etc. since the verification doesn't specify whether the ID applies to the CBP or the CCSSA certification here.

**Comment by mperklin** [comment]
Thanks for submitting this bug in C4's website. 
I'll forward it to the developer.

This repository is for discussion of the CCSS standard, and not the C4 website. As a result I will close this issue.
