### ISSUE TITLE
Add website link to the repository

### ISSUE THREAD

**Issue by paladini** [CryptoConsortium/CCSS#7]
I think you should add the [GitHub pages link](http://blog.cryptoconsortium.org/ccss/) to the proper Github field:

![http://i.imgur.com/l59jCO8.png](http://i.imgur.com/l59jCO8.png)

I didn't found this URL in any place at this repo, I had to Google it. Only later I discovered that the URL was linked into the project title in the readme.md file.

**Comment by Abstrct** [comment]
Good call! Thanks for the suggestion. 

This setting has been updated to point to: http://cryptoconsortium.github.io/CCSS/
